---
- name: Delete old /tmp/composer-project.
  file:
    path: "/tmp/composer-project"
    state: absent
  when: not wordpress_site_exists

- name: Generate Wordpress project with composer package in /tml/composer-project (this may take a while).
  command: >
    {{ composer_path }} create-project
    {{ wordpress_composer_project_package }} /tmp/composer-project
    {{ wordpress_composer_project_options | default('--prefer-dist --no-interaction') }}
  when: not wordpress_site_exists
  become: no
  environment:
    COMPOSER_PROCESS_TIMEOUT: 1200

- name: Ensure wordpress_core_path directory has proper permissions.
  file:
    path: "{{ wordpress_core_path }}"
    state: directory
    owner: "{{ wordpress_core_owner }}"
    group: "{{ wordpress_core_owner }}"
    mode: 0775
  when: not wordpress_site_exists
  failed_when: false

- name: Move Wordpress project files to wordpress_core_path (this may take a while).
  command: >
    cp -r /tmp/composer-project/. {{ wordpress_core_path }}/
    creates={{ wordpress_core_path }}/index.php
  become: no
  when: not wordpress_site_exists
