---
- name: Check if Wordpress is already set up.
  stat: "path={{ wordpress_core_path }}/wordpress/wp-load.php"
  register: wordpress_site
  ignore_errors: true

- name: Define wordpress_site_exists if it's not already defined.
  set_fact:
    wordpress_site_exists: "{{ wordpress_site.stat.exists | default(false) }}"
  when: wordpress_site_exists is not defined

# Build with composer, if configured.
- include_tasks: tasks/build-composer.yml
  when: wordpress_build_composer

# Build a composer project, if configured.
- include_tasks: tasks/build-composer-project.yml
  when: wordpress_build_composer_project

# Install site.
- block:
    - include_tasks: tasks/wp-cli.yml
    - include_tasks: tasks/install-site.yml
  when: wordpress_install_site
