---
# Required Wordpress settings.
wordpress_core_path: "/var/www/app/htdocs"
wordpress_core_owner: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"

wordpress_composer_project_package: "roots/bedrock"

# MySQL databases and users.
wordpress_db_host: localhost
wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_db_password: wordpress

wordpress_install_site: true

wordpress_site_name: "Wordpress"
wordpress_account_name: admin
wordpress_account_pass: admin
wordpress_account_mail: admin@example.com
