---
# Required Wordpress settings.
wordpress_core_owner: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"

# Composer settings
wordpress_composer_install_dir: "/var/www/app/htdocs"
wordpress_composer_project_package: "lammensj/wordplate"

# MySQL databases and users.
wordpress_db_host: localhost
wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_db_password: wordpress

wordpress_install_site: false

# Define how to build Wordpress
wordpress_build_composer_project: false # Clean install using the configured package.

wordpress_build_composer: false # Using an existing composer.json at the configured location.
wordpress_composer_path: "{{ wordpress_composer_install_dir }}/composer.json"

wordpress_core_path: "{{ wordpress_composer_install_dir }}/public"
wordpress_site_name: "Wordpress"
wordpress_account_name: admin
wordpress_account_pass: admin
wordpress_account_mail: admin@example.com
